const zhCN = {
  welfareLottery: {
    copySuccess: '复制成功',
    fillInformation: '请填写以下信息',
    receivedInformation: '已提交信息成功!后续会有工作人员与您联系',
    submit: '确定',
    name: '姓名',
    realName: '请输入您的真实姓名',
    phone: '手机',
    enterPhone: '请输入您的手机号码',
    wrongName: '请输入您的姓名',
    wrongPhone: '号码错误',
    countdownTip1: '还有',
    countdownTip2: '开奖',
    record: '中奖记录',
    redemptionCode: '兑换码',
    winningTime: '中奖时间',
    see: '查看',
    receive: '领取',
    winningResult: '抽奖结果',
    resultTip1: '继续观看直播，赢取更多福利吧~',
    receivePrizes: '领取奖品（自定义）',
    ok: '我知道了',
    numberOfPrizes1: '共',
    numberOfPrizes2: '份',
    receiveByScanCode: '扫码领奖',
    receiveByFillInformation: '填写中奖信息',
    participationConditions: '参与条件',
    winTitle: '恭喜您中奖啦',
    notWinTitle: '很遗憾，没有中奖',
    pressToIdentifyCode: '长按识别二维码',
    joinCounts: '人参与',
    winCounts: '人中奖',
    winnerList: '中奖名单',
    scanToParticipate: '微信扫一扫，立即参与活动',
    copyLiveLink: '复制直播链接',
    participated: '您已参与，等待开奖中',
    scanningToParticipate: '微信扫码参与抽奖',
    invite: '邀请',
    invite1: '人即可参与，',
    invite2: '还需邀请',
    invite3: '人',
    metConditions: '你已满足参与条件',
    participateNow: '立即参与抽奖(custom)',
    copyLinkToParticipate: '复制链接到微信参与活动',
    noRecord: '暂无中奖记录~',
    opened: '已开奖',
    noWinnerList: '暂无中奖名单~',

    commentLabel: '互动区发送评论：'
  },
};

const en = {
  welfareLottery: {
    copySuccess: 'Success',
    fillInformation: 'Please fill in the information',
    receivedInformation: 'submit information successfully!   A staff will contact you later',
    submit: 'ensure',
    name: 'name',
    realName: 'Please enter your real name',
    phone: 'phone',
    enterPhone: 'Please enter your mobile phone number',
    wrongName: 'Please enter your name',
    wrongPhone: 'Wrong mobile phone number',
    countdownTip1: 'And',
    countdownTip2: 'lottery',
    record: 'Winning record',
    redemptionCode: 'Redemption code',
    winningTime: 'Winning time',
    see: 'Check',
    receive: 'Receive',
    winningResult: 'Result',
    resultTip1: 'Keep watching to win more benefits~',
    receivePrizes: 'prize collection',
    ok: 'OK',
    numberOfPrizes1: '',
    numberOfPrizes2: 'total',
    receiveByScanCode: 'Scan the code to receive the award',
    receiveByFillInformation: 'Fill in the winning information',
    participationConditions: 'Participation conditions',
    winTitle: 'Congratulations on your winning',
    notWinTitle: 'Sorry, you did\'t win',
    pressToIdentifyCode: 'Long press to identify the QR code',
    joinCounts: 'participants',
    winCounts: 'winners',
    winnerList: 'List of winners',
    scanToParticipate: 'Scan to participate in activities',
    copyLiveLink: 'Copy live link',
    participated: 'Participated, waiting for the draw',
    scanningToParticipate: 'WeChat scan code to participate in the lottery',
    invite: 'invite',
    invite1: 'people to participate,',
    invite2: 'and ',
    invite3: ' more need to be invited',
    metConditions: 'You have met the conditions to participate',
    participateNow: 'Participate in the draw now',
    copyLinkToParticipate: 'Copy the link and go to WeChat to participate',
    noRecord: 'No winning record~',
    opened: 'Opened',
    noWinnerList: 'No winner list yet~',

    commentLabel: '互动区发送评论：'
  },
};

export default {
  zh_CN: zhCN,
  en,
};
